root: true
env:
  browser: true
  es2021: true
plugins:
  - jest
extends:
  - airbnb
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  semi: [error, never]
  func-names: off
  no-continue: off
